server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sprinkle?serverTimezone=Asia/Seoul&useSSL=false
    username: kuser
    password: pay1234!

logging.level:
  org.hibernate.SQL: debug